# Generated by Django 2.2 on 2019-09-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_tagline', models.CharField(max_length=100)),
                ('service_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
