# Generated by Django 2.2 on 2019-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
