# Generated by Django 2.2 on 2019-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0002_auto_20190908_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_job', models.CharField(max_length=100)),
                ('employee_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_tagline',
            field=models.TextField(max_length=50),
        ),
    ]
