# Generated by Django 2.2 on 2019-09-15 14:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0004_auto_20190915_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
