# Generated by Django 3.0.2 on 2020-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0005_auto_20190915_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(),
        ),
    ]
