# Generated by Django 3.0.2 on 2020-01-13 11:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0006_auto_20200113_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
