# Generated by Django 3.0.2 on 2020-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsclear', '0008_auto_20200115_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialisedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_detail', models.CharField(max_length=300)),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
